from menu.store_menu import *
from menu.wallet_menu import *
from menu.start_menu import *
from menu.settings_menu import *
from menu.support_menu import *
from menu.lot.input_description_menu import *
from menu.lot.input_keys_menu import *
from menu.lot.input_price_menu import *
from menu.lot.input_title_menu import *
from menu.lot.manage_lots_menu import *
from menu.paymet_menu import *
from menu.input_address_menu import *